```{r}
#########################################################################################
# R scripts for Arroyo Hondo Pueblo turkey isotope and faunal data.
# 
# written by Cyler Conrad, Department of Anthropology, University of New Mexico
# cylerc@unm.edu
#
# Results described in:
# Conrad, C., Jones, E.L., Newsome, S.D. and Schwartz, D.W. (in review). 
# Eggshell, Bone Isotopes and Turkey Husbandry at Arroyo Hondo Pueblo. 
# Journal of Archaeoloical Science: Reports.
#
#
# NOTES
# All data required to perform the analyses can be found at
# XXXX (Conrad et al. XXXX). The script was run using R 
# version 3.1.1 on Mac OS X 10.8.5
#
# Reference: 
#
# LICENSE
# 
# The MIT License (MIT)
# 
# Copyright (c) 2015 Cyler Conrad
#   
#   Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#   
#   The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
################################################################################
# set the base directory for knitr to the directory above this one
library(knitr)
opts_knit$set(root.dir = '../')
```

```{r}
###############################################################################
# CHUNK 1: Load libraries.
################################################################################

library(ggplot2) #Version 1.0.0
library(reshape2)
library(vegan)

```

```{r}
###############################################################################
# CHUNK 2-Calculate relative abundance. First, upload the Arroyo Hondo NISP table.
# Second, take all turkey NISP values and divide by the column totals to calculate
# the relative abundance of turtles per stratum. 
################################################################################
fn <- "data/ahNISP.csv" 
ah <- read.csv(fn, stringsAsFactors = FALSE, check.names = FALSE)
ah
#1300-1315
51/(sum(ah$`1300-1315`))
#1315-1330
202/(sum(ah$`1315-1330`))
#1330-1340
186/(sum(ah$`1330-1340`))
#1340-1355
317/(sum(ah$`1340-1355`))
#1355-1365
83/(sum(ah$`1355-1365`))
#1365-1370
92/(sum(ah$`1365-1370`))
#1380-1410
51/(sum(ah$`1380-1410`))
#1410-1425
152/(sum(ah$`1410-1425`))
```

```{r}
###############################################################################
# CHUNK 3-Figure 6a: Plot of relative abundance. Use relative abundance
# values that were previously calculated to create plot of changing abundance 
# through time. 
################################################################################

fn <- "data/fig6a.csv" 
ra <- read.csv(fn, stringsAsFactors = FALSE, check.names = FALSE)
ra
str(ra)

ggplot(ra, aes(ra$`Date (C.E.)`, ra$`Relative Abundance`)) +
  geom_bar(binwidth = 1.0, stat="identity") +
  coord_flip() +
  xlab("Date (C.E.)") +
  ylab("Relative Abundance") +
  ylim(0.0,0.3) +
  theme(
  legend.position="",
  axis.text.x = element_text(vjust=0.5, color="black", size=18),
  axis.text.y = element_text(vjust=0.5, color="black", size=18), 
  axis.title.y = element_text(vjust=1.0, color="black", size=18),
  axis.title.x = element_text(vjust=0.1, color="black", size=18),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(), 
  axis.line = element_line(colour = "black"),
  strip.text.x = element_text(size=15),
  strip.background = element_rect(colour="black", fill="white"))

fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_6a.png",
       dpi = 600, units = "mm",
       height = fig_width/1.6, width =  fig_width)
  
```

```{r}
###############################################################################
# CHUNK 4-Calculate taxonomic evenness. Use the diversity function in vegan to 
# calculate the inverse of Simpson's per stratum. 
################################################################################
diversity(ah$`1300-1315`, index = "invsimpson")
diversity(ah$`1315-1330`, index = "invsimpson")
diversity(ah$`1330-1340`, index = "invsimpson")
diversity(ah$`1340-1355`, index = "invsimpson")
diversity(ah$`1355-1365`, index = "invsimpson")
diversity(ah$`1365-1370`, index = "invsimpson")
diversity(ah$`1380-1410`, index = "invsimpson")
diversity(ah$`1410-1425`, index = "invsimpson")
```

```{r}
###############################################################################
# CHUNK 5-Figure 6b: Plot of 1/D. Use 1/D values that were previously 
# calculated to plot changing evenness through time.
################################################################################

fn <- "data/fig6b.csv" 
even <- read.csv(fn, stringsAsFactors = FALSE, check.names = FALSE)
even
str(even)
 
ggplot(even, aes(even$`1/D`, even$`Date (C.E.)`, group=1)) +
  geom_point(size=4) +
  xlim(0.0,15.0) +
  xlab("1/D") +
  ylab("Date (C.E.)") +
  theme(
  legend.position="",
  axis.text.x = element_text(vjust=0.5, color="black", size=18),
  axis.text.y = element_text(vjust=0.5, color="black", size=18), 
  axis.title.y = element_text(vjust=1.0, color="black", size=18),
  axis.title.x = element_text(vjust=0.1, color="black", size=18),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  panel.background = element_blank(), 
  axis.line = element_line(colour = "black"),
  strip.text.x = element_text(size=15),
  strip.background = element_rect(colour="black", fill="white"))

fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_6b.png",
       dpi = 600, units = "mm",
       height = fig_width/1.6, width =  fig_width)
  
```

```{r}
###############################################################################
# CHUNK 6-Figure 7: Plot of carbon and nitrogen isotopic data from Arroyo Hondo Pueblo.
################################################################################

fn <- "data/fig7.csv"
turkey <- read.csv(fn, stringsAsFactors = FALSE, check.names = FALSE)
turkey
str(turkey) 

ggplot(turkey, aes(x = d13C, y = d15N)) + 
  geom_point(aes(), size=3.5) + 
  xlab(expression(paste(delta^{13},'C'))) + 
  ylab(expression(paste(delta^{15},'N'))) + 
  xlim(-21.0,-5.0) +
  ylim(2.0,12.0) +
  theme(
  legend.position="",
  axis.text.x = element_text(vjust=0.5, color="black", size=18),
  axis.text.y = element_text(vjust=0.5, color="black", size=18), 
  axis.title.y = element_text(vjust=1.0, color="black", size=22),
  axis.title.x = element_text(vjust=0.1, color="black", size=22),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), 
  panel.background = element_blank(), 
  axis.line = element_line(colour = "black"))

# save plot
fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_7.png",
       dpi = 600, units = "mm",
       height = fig_width/1.6, width =  fig_width)
```

```{r}
###############################################################################
# CHUNK 7-Analysis: Calculate means and standard deviations for carbon and 
# nitrogen isotopic data. 
################################################################################

turkey
mean(turkey$d13C)
#-8.22625
sd(turkey$d13C)
#1.841556
mean(turkey$d15N)
#9.02125
sd(turkey$d15N)
#1.424976
```


